pipeline {
    
        agent {
        docker {
            image 'adoptopenjdk/maven-openjdk11'
            args '-v /root/.m2:/root/.m2'
        }
    }
    environment {
        TIMESTAMP = sh(script: "echo `date +%s`", returnStdout: true).trim()
    }

    stages {
        stage('Build container and push') { 
            steps {
                dir("my-api") {
                    sh 'mvn -B -DskipTests clean install'
                    sh 'cp target/my-api-1.0.1.${TIMESTAMP}.jar src/main/docker/my-api.jar'
                    sh 'mvn docker:build docker:push'
                }
            }
        }
    }
}